/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bolocdanhmuc`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/chatboxai`; params?: Router.UnknownInputParams; } | { pathname: `/Checkout`; params?: Router.UnknownInputParams; } | { pathname: `/CheckoutSuccess`; params?: Router.UnknownInputParams; } | { pathname: `/ctsp`; params?: Router.UnknownInputParams; } | { pathname: `/danhgia`; params?: Router.UnknownInputParams; } | { pathname: `/DanhMucPC`; params?: Router.UnknownInputParams; } | { pathname: `/favorite`; params?: Router.UnknownInputParams; } | { pathname: `/ForgotPasswordScreen`; params?: Router.UnknownInputParams; } | { pathname: `/hipc`; params?: Router.UnknownInputParams; } | { pathname: `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/pay`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/Searchscreen`; params?: Router.UnknownInputParams; } | { pathname: `/SignUpSreen`; params?: Router.UnknownInputParams; } | { pathname: `/sosanhsanpham`; params?: Router.UnknownInputParams; } | { pathname: `/theodoidonhang`; params?: Router.UnknownInputParams; } | { pathname: `/thongbao`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/bolocdanhmuc`; params?: Router.UnknownOutputParams; } | { pathname: `/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/chatboxai`; params?: Router.UnknownOutputParams; } | { pathname: `/Checkout`; params?: Router.UnknownOutputParams; } | { pathname: `/CheckoutSuccess`; params?: Router.UnknownOutputParams; } | { pathname: `/ctsp`; params?: Router.UnknownOutputParams; } | { pathname: `/danhgia`; params?: Router.UnknownOutputParams; } | { pathname: `/DanhMucPC`; params?: Router.UnknownOutputParams; } | { pathname: `/favorite`; params?: Router.UnknownOutputParams; } | { pathname: `/ForgotPasswordScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/hipc`; params?: Router.UnknownOutputParams; } | { pathname: `/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/pay`; params?: Router.UnknownOutputParams; } | { pathname: `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/Searchscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/SignUpSreen`; params?: Router.UnknownOutputParams; } | { pathname: `/sosanhsanpham`; params?: Router.UnknownOutputParams; } | { pathname: `/theodoidonhang`; params?: Router.UnknownOutputParams; } | { pathname: `/thongbao`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/bolocdanhmuc${`?${string}` | `#${string}` | ''}` | `/cart${`?${string}` | `#${string}` | ''}` | `/chatboxai${`?${string}` | `#${string}` | ''}` | `/Checkout${`?${string}` | `#${string}` | ''}` | `/CheckoutSuccess${`?${string}` | `#${string}` | ''}` | `/ctsp${`?${string}` | `#${string}` | ''}` | `/danhgia${`?${string}` | `#${string}` | ''}` | `/DanhMucPC${`?${string}` | `#${string}` | ''}` | `/favorite${`?${string}` | `#${string}` | ''}` | `/ForgotPasswordScreen${`?${string}` | `#${string}` | ''}` | `/hipc${`?${string}` | `#${string}` | ''}` | `/HomeScreen${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/pay${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `/Searchscreen${`?${string}` | `#${string}` | ''}` | `/SignUpSreen${`?${string}` | `#${string}` | ''}` | `/sosanhsanpham${`?${string}` | `#${string}` | ''}` | `/theodoidonhang${`?${string}` | `#${string}` | ''}` | `/thongbao${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bolocdanhmuc`; params?: Router.UnknownInputParams; } | { pathname: `/cart`; params?: Router.UnknownInputParams; } | { pathname: `/chatboxai`; params?: Router.UnknownInputParams; } | { pathname: `/Checkout`; params?: Router.UnknownInputParams; } | { pathname: `/CheckoutSuccess`; params?: Router.UnknownInputParams; } | { pathname: `/ctsp`; params?: Router.UnknownInputParams; } | { pathname: `/danhgia`; params?: Router.UnknownInputParams; } | { pathname: `/DanhMucPC`; params?: Router.UnknownInputParams; } | { pathname: `/favorite`; params?: Router.UnknownInputParams; } | { pathname: `/ForgotPasswordScreen`; params?: Router.UnknownInputParams; } | { pathname: `/hipc`; params?: Router.UnknownInputParams; } | { pathname: `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/pay`; params?: Router.UnknownInputParams; } | { pathname: `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/Searchscreen`; params?: Router.UnknownInputParams; } | { pathname: `/SignUpSreen`; params?: Router.UnknownInputParams; } | { pathname: `/sosanhsanpham`; params?: Router.UnknownInputParams; } | { pathname: `/theodoidonhang`; params?: Router.UnknownInputParams; } | { pathname: `/thongbao`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
